---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qfpuksur/public_html/nvwweddings
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R sass $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    